### ISSUE TITLE
Documentation link in README.md is broken

### ISSUE THREAD

**Issue by ghost** [AlbanAndrieu/ansible-jenkins-slave#3]
The documentation link in the following line goes to a page that does not exist on ReadTheDocs. I could not find the correct page to suggest.

"More information about alban.andrieu.jenkins-slave can be found in the official alban.andrieu.jenkins-slave documentation."

**Comment by AlbanAndrieu** [comment]
Thanks a lot.

Indeed, I never managed to find time to create a proper documentation using ReadTheDocs.
I have commented the link to avoid confusion until I found some time to do it properly

Generator fixed with commit https://github.com/AlbanAndrieu/ansible-nabla/commit/1340e4b6439dfa13952b9c8d01334053807cb3df

**Comment by piotrkochan** [comment]
There is still a link
https://docs.debops.org/en/latest/ansible/roles/ansible-jenkins-slave/docs/

and it still does not work
